name: aula04
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  shared_preferences: ^2.2.2
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^6.1.0
  lottie: ^3.0.0  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/gifs/    # ou liste arquivos específicos:
    # - assets/gifs/salsicha.gif
    # - assets/gifs/cat.gif
    # - assets/gifs/dog.gif
